import {
  burger,
  meal,
  coffee,
  croissant,
  fruitJuice,
  pizza,
  paypal,
  visa,
  creditCard,
} from "../assets";

export const FakeDataCardsInfo = [
  {
    id: "res1",
    name: "Asker Abinin Yeri",
    img: burger,
    paymentMethod: "paypal",
    paymentImg: paypal,
    rate: 5.0,
    time: "30 - 35",
    delivery: 10,
    lowest: "75",
    location: "Turkey",
  },
  {
    id: "res2",
    name: "اوسيس",
    img: meal,
    paymentMethod: "visa",
    paymentImg: visa,
    rate: 5.0,
    time: "40 - 45",
    delivery: 0,
    lowest: "150",
    location: "Lebanon",
  },
  {
    id: "res3",
    name: "بن الشام",
    img: coffee,
    paymentMethod: "creditCard",
    paymentImg: creditCard,
    rate: 4.9,
    time: "35 - 40",
    delivery: 0,
    lowest: "100",
    location: "Syria",
  },
  {
    id: "res4",
    name: "Croissant Home",
    img: croissant,
    paymentMethod: "paypal",
    paymentImg: paypal,
    rate: 4.5,
    time: "20 - 30",
    delivery: 0,
    lowest: "50",
    location: "Lebanon",
  },
  {
    id: "res5",
    name: "Cocktails",
    img: fruitJuice,
    paymentMethod: "paypal",
    paymentImg: paypal,
    rate: 4.0,
    time: "15 - 20",
    delivery: 10,
    lowest: "50",
    location: "Egypt",
  },
  {
    id: "res6",
    name: "بيتزا",
    img: pizza,
    paymentMethod: "visa",
    paymentImg: visa,
    rate: 5.0,
    time: "25 - 30",
    delivery: 15,
    lowest: "175",
    location: "Syria",
  },
];
